### ISSUE TITLE
Pin or parameter 'compensation.clear' not found

### ISSUE THREAD

**Issue by zmrdko** [scottalford75/LinuxCNC-3D-Printing#7]
hello,
I am trying to use this compensation component, but I am getting error:
![image](https://github.com/user-attachments/assets/35bd7334-78eb-4250-bdff-c8240f2bdcb2)
when I try to enable compensation.
Did I miss something?
i have installed component by using
`sudo halcompile --install --userspace compensation.py`
hal file:
![image](https://github.com/user-attachments/assets/10a61e9d-c27a-484a-b72c-435edec4058e)
im using axis sim_mm

**Comment by DauntlessAq** [comment]
I believe the reason why compensation.clear is being shown as the pin that isn't found (rather than the others) may simply be because it's the first pin listed in HALSHOW when the component fails when compensation is enabled.

**Regarding solutions:**

Have you been able to get External Offsets working without compensation.py by manually setting the parameters in HALCMD or your HAL file?

Did you definitely make the changes to your INI file to enable external offsets (setting an acceptable value for OFFSET_AV_RATIO and enabling HALUI)?

Is the probe-results.txt file present and formatted correctly? It should just be rows of XYZ data.
You can test with this 9 point file: [probe-results.txt](https://github.com/user-attachments/files/17081741/probe-results.txt)

Have you confirmed that HALCOMPILE placed compensation.py in the correct directory for axis sim_mm?

I see you wrote: `loadusr -Wn compensation compensation probe-results.txt cubic`
Can you try this: `loadusr -Wn compensation python compensation.py probe-results.txt cubic`

Have you installed all the dependencies (numpy, scipy and enum34)?
I see you're running LinuxCNC 2.9.3 so that won't be an issue (external offsets were introduced in 2.8.0).

Hope this helps!

**Comment by zmrdko** [comment]
Thank you, it's solved already.
